# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The maximum number of points on a line
#' @description Find the maximum number of points on the two-dimensional plane that can be connected into a straight line
#' @param points Two dimensional matrix, the first column is x and the second column is y
#' @return the mximum number
#' @examples
#' \dontrun{
#' points<-matrix(c(1,1,2,2,3,3),3,2,byrow = TRUE)
#' maxPoints(points)
#' }
#' @importFrom Rcpp evalCpp
#' @useDynLib StatComp22032
#' @export
maxPoints <- function(points) {
    .Call('_StatComp22032_maxPoints', PACKAGE = 'StatComp22032', points)
}

